name: weather_assistant
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  go_router: ^8.0.5
  riverpod_annotation: ^2.1.1
  shared_preferences: ^2.1.2
  google_fonts: ^4.0.4
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  freezed_annotation: ^2.2.0
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  dio: ^5.2.1+1
  retrofit: ^4.0.1
  cloud_firestore: ^4.8.2
  flutter_swipe_action_cell: ^3.1.2
  weather_pack: 0.0.2
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  json_serializable: ^6.7.0
  freezed: ^2.3.5
  retrofit_generator: ^7.0.7

flutter:
  uses-material-design: true

  assets:
  - assets/illustrations/
