name: Develop Workflow

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and Test
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      
      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test
          