name: IOS TestFlight Deployment

on:
  push:
    branches:
      - main

jobs:
  ios:
    runs-on: macos-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        cache: true

    - name: Setup Fastlane
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
        rubygems: latest

    - name: Install Setup AppStore files
      run: |
        cd ios
        bundle install
        cd ..
        echo "$GCKEY_FILE" > ./ios/gc_keys.json
        echo "test" > ./ios/coucou.txt
      shell: bash
      env:
        
        GCKEY_FILE: ${{ secrets.GCKEY_FILE }}


    - name: Build and Deploy
      run: |
        flutter pub get
        cd ios
        ls -al
        du -sh gc_keys.json
        du -sh coucou.txt
        cat coucou.txt
        fastlane beta
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        APP_STORE_CONNECT_API_KEY: ${{ secrets.AUTHKEY_FILE }}
