name: IOS TestFlight Deployment
on:
  push:
    branches:
      - main

jobs:
  ios:
    runs-on: macos-12
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        cache: true

    - name: Setup Fastlane
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
        rubygems: latest

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: "14.2"

    - name: Install Setup AppStore files
      run: |
        cd ios
        bundle install
        cd ..
        echo $GCKEY_FILE > ./ios/gc_keys.json
        echo $APP_STORE_CONNECT > ./ios/AuthKey.p8
      shell: bash
      env:
        GCKEY_FILE: ${{ secrets.GCKEY_FILE }}
        APP_STORE_CONNECT: ${{ secrets.AUTHKEY_FILE }}
        KEY_ID: ${{ secrets.APPLE_KEY_ID }}


    - name: Build and Deploy
      run: |
        flutter pub get
        cd ios
        fastlane beta
      env:
        APP_STORE_CONNECT_KEY: ${{ secrets.AUTHKEY_FILE }}
