name: Release workflow

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  release-draft-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Nécessaire pour récupérer tous les tags

      - name: Deploy from internal to production
        run: |
          if [ "${{ github.event.pull_request.merged }}" = "true" ]; then
            echo "Pull request merged"
            echo "Deploying to production"

      