name: CI

on:
  push:
    branches:
      - 'release/**'

jobs:
  tag_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Semantic Versioning
        id: semver
        uses: paulhatch/semantic-version@v4.0.2
        with:
          branch: ${{ github.ref }}
          format: '${major}.${minor}.${patch}-beta.${increment}'
          tag_prefix: ''

      - name: Create tag
        run: |
          echo "Creating tag ${{ steps.semver.outputs.version }}"
          git config --local user.email "
          git config --local user.name "
          git tag -a ${{ steps.semver.outputs.version }} -m "Tag ${{ steps.semver.outputs.version }}"
          git push origin ${{ steps.semver.outputs.version }}